// ====================================
// <copyright file="EventGenerator.cs" company="Spicco D'Aura">
// Copyright (c) Spicco D'Aura. All rights reserved.
// Licensed under the CC BY-SA 1.0 License.
// </copyright>
// ====================================

using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Avian.SourceGen
{
    [Generator(LanguageNames.CSharp)]
#pragma warning disable RS1036
    public class EventGenerator : IIncrementalGenerator
#pragma warning restore RS1036
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (node, _) => node is StructDeclarationSyntax { BaseList: not null },
                transform: (ctx, _) =>
                {
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol((StructDeclarationSyntax)ctx.Node) as INamedTypeSymbol;
                    return symbol?.Interfaces.Any(i => i.Name == "IEvent") == true ? symbol.Name : null;
                }
            ).Where(name => name != null);
            
                
            context.RegisterSourceOutput(provider, (ctx, name) =>
            {
                string sourceCode = $@"
// <auto-generated>This file is automatically generated by Avian.SourceGen.EventGenerator.</auto-generated>

namespace Avian.Event;

public static class {name}Extensions
{{
    public static void Dispatch(this Dispatcher dispatcher, {name} eventData)
    {{
        dispatcher.Publish(eventData);
    }}
}}
";
                ctx.AddSource($"{name}Extensions.g.cs", sourceCode);
            });
        }
    }
}